### ISSUE TITLE
Weirdness in the perceptron learner

### ISSUE THREAD

**Issue by interactiveaudiolab** [interactiveaudiolab/course-deep-learning#2]
Hmm...so when a point is near to the plotted decision surface...but on the wrong side of the line... the perceptron doesn't update the decision surface. Is there a problem with the decision surface plotting or is there a problem with the perceptron code? Not sure.  Have a look at this.
<img width="391" alt="Screen Shot 2022-01-27 at 2 43 42 PM" src="https://user-images.githubusercontent.com/1305144/151455664-5abc948f-329f-44fc-aae5-f7b79f4d659d.png">

**Comment by oreillyp** [comment]
It's looking like a plotting issue - the weights and decision boundary are shown after the update, so what we'd be looking for in the above example is a difference between the weights at steps 4 and 5, not 5 and 6.  When I run the perceptron with "verbose=True", it looks like the actual weight updates are being performed correctly.

I agree that this is very unclear, and so I've modified the plotting code to plot the weights, data, and decision boundary *before* the weight update takes place. Hopefully, the plots now illustrate the perceptron learning process more clearly.
