### ISSUE TITLE
Notebook4_adversarial_examples Audio mnist download bug

### ISSUE THREAD

**Issue by bryan-pardo** [interactiveaudiolab/course-deep-learning#4]
I couldn't download audio mnist. See the attached image for the details
<img width="710" alt="Screen Shot 2022-02-16 at 5 26 27 PM" src="https://user-images.githubusercontent.com/26678616/154386630-1823c9f6-edbb-4832-9971-7367c5dde247.png">
.

**Comment by interactiveaudiolab** [comment]
Good. Thanks.
